# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7b5fd751-c45d-450a-88de-71474d16c9d4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7b5fd751-c45d-450a-88de-71474d16c9d4".device = "/dev/disk/by-uuid/7b5fd751-c45d-450a-88de-71474d16c9d4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9A02-4A45";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ffeb8c8b-0b47-4b51-9d3a-d21ca17e832a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
